sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  global:
    - PKG_REPOTYPE=community
    # packagecloud API token for citus-bot
    - secure: "DrgnMSsX/XvMZltIvnE9VTGFRVDWfLafTdJwjd//vgLZ8PDNJ/UHm7Vr7dBoNIR0LytMnBgGWRfz6oi5HNgNLc2GnTfv4muyjK8i2OTmvs4ALKBoxiI888+nhh6jhf9WYvCKGNolTspxP3dgVB9B2NiGCyKBN2hCzts59fqtGED+kSE0Bda/pBnDHml7IMMHwdXB3V9KNOdD42TE8Bf7B/XpI69JZfaYrBqGYidVaInqaVEFjNOmkndLEXl5cf82YCWAYCJ/VlKgcg5Zi38kpiYn7ZjQ6QuVibbxOWG5hSQym6UYy/5HieEajo6aaamaun5ATcUMfRNtrQBGiwAkI0lPjrx8TPE00EfFJ6lryUa3eABs9dntI3veZPQdh3w8AHEbUiRb0VVJ934STlKllRskpMmE1MT7VqRnYHAsVPrY0J2sXnmAGPHf1B1LgJE3mljIVJVsTHJc/GaRmXQuUxyrU32BkN1Ie92gZjaDeVddFiQh0KND0HMtF0CmbPy5t8tRQnMVVcIKLQUfMF8ELGnqw+v5rxBho8w+mZ4Jg6MR1Z0wIs63+4/yHLmD4l/09AA6kLZVEuJYqwV71nEL5QI561S2lDTOh8c0toe/GMkmdO+9aQ1aASjixkuWnDj8Ok22fWFkOojt861FXGOszyT2DbSJweFrKPs7Cv8XV2M="
    # GitHub ("Packaging") API token for citus-bot
    - secure: "zb6AHEUEvpCnWb4zRTsWTWVmMWNHkzz4c+UUgABaXYysJHCfBNiu5X4Da/jusCPY9GH4XFX8GPCiR69ZKw/LDnzHgXoH2pmda02CZM6SHjRGd0MrlBl0hF8YbHiBFi6/nH7kF0ODX+SepfJlFq8LQq6HVONz6QQl0FW0Rg1qnNaDMMi6L9NBBSDyuYCUdY05lgNeIyG8LyIErvlNA8U86VxOHp/KKbNaNx0Cs/tpDWNeW1v1rxa6EXtt8pxyc4u09V9csyFcglizkWEi98aqBTqyCa4hgIK3anog51vAg997cPOUu+ENUpwsio2JMorXalzNszBtpbO9u15+hLRHAoSL56hRdar3fTCuyyXpKapyNZ5Xxa8bYmgLDSJ2lS3zDl6fUfJWVqfzDWx1BuYVGjmJquYMVGKDiBu6iiOx7M/L8Kwof/ioe1LWro92a+S2KKgmXJfxNm4//F2EK+n++GNMZzOsfW+HSVhZ5sXt/tN9eOGmRQ4jWOZK7ycdpB+zMtxYDur/D46oLGAJhY88YqJaBbx0Jk0EMzSfM1eSoGcXEfLfwzGTm3MFnG/IJ3BPW1pkf5s2gMofUssGFitqnDZ7wlexrwA6qPMPIafW+yn5m4wwQwAxk20Y/kOREKHYDP6X6AbQNmfUk93/djYLjd/gGYLS3xvkNOLBWq2CCD8="
    # passphrase for packaging gpg secret key
    - secure: "pZmrxStWj0vXaG/YAyJORvxfaKQHvr+O+66yjFF52gQTVd2zNb83Mn4zDLNqMwU3nkXEKYuFbpXKbDSMX9zNbE7W/w1ARSa8MVXnMVM3jbj+OCaBu7fyVrA0tvT3EZkMh943paTRcSyPSzd61P3CNOkcY1RycDHBbJtNrzSdUbdAy6//TWgNxC66dxSeHASRJIIs49caxQssMMSGRgC5aGH4KLU5eSdP3wnWDEHr+aLqaI2DF2W3lNMI0WJwtGN6cLEYzAsA3BkoPoYRFDd4jjTpolVdrFBXRaT1EIg0FXjsvjyFrQfQLBIqvSx42H5w4rCIYoKYYgRgCKDATLK8XxPbFsgPKLVSHFD6t9ebuYacYxS20oMakkqj5e98qMIWe2vkm+V9YNeADIlhYT+NsF9Kug2B6pLK+U+Hhj6TldFpP18snPXttRKzsg9QrGbnBUVq2wv60U7/3pWs+T3tpr9bIFyaUYbRRAwl/hv2hVkFiSdsiLB6tJphbILB7EDKBCu1iK9PC9tlYoGrqptRxj6bmlawOvcnEKRtoPNJ9eyrvHPDd8FmmW6xWbq89zJ97Ztl7VR8CzNePqvG9vwdtJigXovuXfzu4CHX+jOt3jvllB6rMprsK5r++qBzh1SS24sYqo/APtUfoYdkleWhC+tSuhbucZb2yGUCMo/ZhDo="
    # DOCKER_USER parameter to login docker
    - secure: "k0GxOWjL4Au+CtdDLfVe7Vg1X5j7NDpGeZBGmXM2waApPMmQTs92naK+UqaT7dmZJGD5JgFnMrQzD5+CSodXvIwT0WE0wRYvPaHV0khMJckrJGThECuRucwzN/EicqkROHZ7hG5tDLZDbP+hjZJUlh2nCjCrxZDwLLOGU3URHoRzfcqBMBN+qd13hqQa5ynGHJr4Ol5PfhyuLqVdpcojVnfeZf5+br2xRgNHXn0xq62UIdDuNWpKHNf9vkdaYPHi/WSg1NtI7fX1rbBsgvnQZZrRQHYDp+Y8kbo3S3crEu6vyNF4cRodFSfNzbsD1Syc0t67/TnHRbMnbGhd9DTjvaP40E2lbrXnwK0Ekdkf4I1/R0k1Ralo5hKRMV/CJ1jpnbcujBOKbDGVVx7sJJ3P6vY+vS1XR6XbevHnccDtTa40QtnJX2iuYo/bYPDftvJSE1OyRLvQEzE2EFzD0VRNFaamyH8/h4fdhM7f8LL2AjDnTx++qwjk0DfNN4SNVUzz8jasKSgPwxY/TAvRvAn+6ON/cJlyqCbKysp+cVoch3Lh1jpGubFawv5mP8l2egQVOkxEpuCYNICjZpFclKP7gzxZMM9to1lBkSfoA5zRqLmvSOvIqqOfAi7i7BEMUHgNuGnZ4LpsCTngrdbHqg/02K0utDBeUXMzlInhpcvOI+4="
    # DOCKER_PASS parameter to login docker
    - secure: "SqG5SZhshlllOALPks5f+EHLp4387prRJag73JTo7ldL/C6UidK+J2CWA/2CnCTG43VFhFPs/OQLY59n0jSFeLFlNJnR0FdxT6pSThzDwLHrjmNCwZo56lafJFACVL1nIhHfdZk3jSrTQ36GfmXIimsHLctLf+w0IRP8qGljaAr3+ebjgEPz/TXB+kBNr+S9uVQRQ7/bTChHcpit8ubcG66lzSPYSB+NyrroxnjePOVjDs5scosjPE4kjGM4lr/xhfhkXprcR/bP1+eL+KGDbU79u3CBOIC3kWe2tvbT9skQ/MuPLY4eSXk9H0QHnJ6twMktRTmMR6btZEUdIIh9bb8Ao8sVPISJSfxRS8Mghm37tb0BQ314wR0CuqVY07bm/2RT/Yxs9jSYUKwvKxGdOGW2mlgHWiVuHzT4y8b8Up5NuxnDKc8T9G6t+LSjqm4ZEbt55LVgZJIVXVCfgwlT+x1QkXqUIxMXab/EebgujOM54sqoK40cI1Rj4W8M2ta1mj4M2NlxJUTrROJfWYI9japRSx3sv741jEcus1G0sNn++4yXI7zjcOTxiDSdUUr5vjxbQUrzAGvI1YF1Z49Z43jW617oAEgMqCB6E5S904pUe5XY1wO+PMeAV67UWOXCI8GszpKZ3Pu9PDO4fGGg5Rvu47tMrfhEjyr766Q+M3U="

  matrix:
    - TARGET_PLATFORM=el/8
    # Oracle Linux 8 does not exist in PackageCloud
    #- TARGET_PLATFORM=ol/8
    - TARGET_PLATFORM=el/7
    - TARGET_PLATFORM=ol/7
    # Oracle Linux 6 is old and it doesn't work with static assert:
    # https://github.com/citusdata/pg_auto_failover/issues/200
    # - TARGET_PLATFORM=ol/6
    - TARGET_PLATFORM=debian/buster
    - TARGET_PLATFORM=debian/stretch
    - TARGET_PLATFORM=ubuntu/focal
    - TARGET_PLATFORM=ubuntu/bionic
    - TARGET_PLATFORM=ubuntu/xenial
before_install:
  - git clone -b v0.7.21 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - export PACKAGING_SECRET_KEY="$(openssl aes-256-cbc -K $encrypted_a39e3f1ee8ba_key -iv $encrypted_a39e3f1ee8ba_iv -in signing_key.asc.enc -d | base64)"
  - echo "${DOCKER_PASS}" | docker login --username ${DOCKER_USER} --password-stdin
install: true
script: |
  if [ ${TRAVIS_EVENT_TYPE} == 'push' ] || [ ${TRAVIS_EVENT_TYPE} == 'pull_request' ] || [ ${TRAVIS_EVENT_TYPE} == 'api' ]; then
  echo "Travis Event Type is ${TRAVIS_EVENT_TYPE}"
  build_new_release
  elif [ ${TRAVIS_EVENT_TYPE} == 'cron' ]; then
  echo "Travis Event Type is ${TRAVIS_EVENT_TYPE}"
  build_new_nightly
  docker logout
  fi
deploy:
  - provider: packagecloud
    username: "citusdata"
    repository: $PKG_REPOTYPE
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/releases"
    on:
      branch: "all-pgautofailover"
      condition: -d "pkgs/releases"
  - provider: packagecloud
    username: "citusdata"
    repository: "$PKG_REPOTYPE-nightlies"
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/nightlies"
    on:
      branch: "all-pgautofailover"
      condition: -d "pkgs/nightlies"

