sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  global:
    # GitHub ("Packaging") API token for citus-bot
    - secure: "uEIo5Gl2T6/4MSTay4Wioo8P2xuuymcLV0H/66JZGFoglwR+2okuphUKikmiayjskksvpChDyEebuju//J1Il0TDZ+lk706cKulQP0rrqwZc9o9bpb0Pq9WOgPORQ2LjHA7fO5/k+jpSQQic67Zyvtbv112Py43NZ/xAEV554WcAkztEpFG8lyajTZZopMjNxyzswBv7CXcvAZDc2LvZJ/caqkVzzozI6Zw8XuP4reHfNW97M/PqeX34JibHa2rRhKJnc9fDiCcXlGleOFbkwlUO1pHQY8aSreemmMJhhx20xtpKlLrTzTXN9VMNzx/3uiFryg1vQvzJRtC5P6RlteUMnjJ3BYPMxUEdeAcz2/O3z1mIBtjbcvZdUKzQYMbMwl/Wn+7uI89N36THGq39SYjjqCSeWdP+VgJ8dPy5MfE4wB4qwkPBC1eljGWe0RtAy7Op9O+13PPeQ+ZhtbB+3IW7aWdmFUFGyOmtOYULzksqCdKjoW/sCBuFymbwH3LUkBQBDfNZHWEGUQCam4ZzYckvCHv0fBzPwkRCpknhSgRKtZuu/C8m3yxns2lhvFR8PFHi9uMoXQOndP4H6qrVHSftga3tRRDJUZryF/A9XrGo3I8VwumVOX9tIiQviuwUyMtaagRzmoHNfUU6T+7sjFjtb7Auw3s84gVnRsqGDYQ="
    # PGXN password for citusdata
    - secure: "tA0sEJpfzC6r4CcGegFyt0B16pGdhveVsZqyEBhF6niKojgw7b/sZC8SA0eQXAgYfSpQs3t+WCsitNW9Wgbot/xkZQltKFTY//YZRMvHNGQenmiOQ03KpCHaR9QqtS1ZziYNY1W4H+qVxTHKCHISTCEj/oq+U3w/rSMvxBz8yGtVedGtBvZP8JfC2AepAqJAwMPfR71bYbAXNIJqywR5Hmd0zB+nAKNaXUY7FkyyZm89zXrkjMY467RsNlf9V1BbwpNtyAHNIwES97qEqTiMMmutW62K54FjibH8GmktzcmN0FQnXPaZoPzMf95RcYTgc1FPbZqgZodWf73HezpkrBsNiZ6DzACER5meLVV39ehw92iOW7noMN7qTsmtM7q64ERSILPdcTrN/xR0oc9JmdCTdeo1san7p0StEz88G1S3oPVNIEgVz6wxpxySWMnGlvEAsHDtFDPC0A4RiNixPKZIJsvHQU4r54vieJHJpqGuWGyKJtNZ4yitW89a4GZCX3b4XKuUR2swscrIxuKKolABwcZgFanZXp16av3z2qmKdV/o8cNDL2+pdpkqGErjbWvPo+JMh3Ia87FeYvbVRj8WjBGs7NCsC4p9NtulnEKHoUrcjsD961r4Oo73ZB5oYKF+k1ZV86+Qw8Tgl3M+TxQN/tOscIQ6WPSKN3AOR80="
branches:
  only: ['pgxn-citus']
before_install:
  - git clone -b v0.7.1 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
install: true
script: release_pgxn
