sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  global:
    - PKG_REPOTYPE=community
    # packagecloud API token for citus-bot
    - secure: "DrgnMSsX/XvMZltIvnE9VTGFRVDWfLafTdJwjd//vgLZ8PDNJ/UHm7Vr7dBoNIR0LytMnBgGWRfz6oi5HNgNLc2GnTfv4muyjK8i2OTmvs4ALKBoxiI888+nhh6jhf9WYvCKGNolTspxP3dgVB9B2NiGCyKBN2hCzts59fqtGED+kSE0Bda/pBnDHml7IMMHwdXB3V9KNOdD42TE8Bf7B/XpI69JZfaYrBqGYidVaInqaVEFjNOmkndLEXl5cf82YCWAYCJ/VlKgcg5Zi38kpiYn7ZjQ6QuVibbxOWG5hSQym6UYy/5HieEajo6aaamaun5ATcUMfRNtrQBGiwAkI0lPjrx8TPE00EfFJ6lryUa3eABs9dntI3veZPQdh3w8AHEbUiRb0VVJ934STlKllRskpMmE1MT7VqRnYHAsVPrY0J2sXnmAGPHf1B1LgJE3mljIVJVsTHJc/GaRmXQuUxyrU32BkN1Ie92gZjaDeVddFiQh0KND0HMtF0CmbPy5t8tRQnMVVcIKLQUfMF8ELGnqw+v5rxBho8w+mZ4Jg6MR1Z0wIs63+4/yHLmD4l/09AA6kLZVEuJYqwV71nEL5QI561S2lDTOh8c0toe/GMkmdO+9aQ1aASjixkuWnDj8Ok22fWFkOojt861FXGOszyT2DbSJweFrKPs7Cv8XV2M="
    # GitHub ("Packaging") API token for citus-bot
    - secure: "uEIo5Gl2T6/4MSTay4Wioo8P2xuuymcLV0H/66JZGFoglwR+2okuphUKikmiayjskksvpChDyEebuju//J1Il0TDZ+lk706cKulQP0rrqwZc9o9bpb0Pq9WOgPORQ2LjHA7fO5/k+jpSQQic67Zyvtbv112Py43NZ/xAEV554WcAkztEpFG8lyajTZZopMjNxyzswBv7CXcvAZDc2LvZJ/caqkVzzozI6Zw8XuP4reHfNW97M/PqeX34JibHa2rRhKJnc9fDiCcXlGleOFbkwlUO1pHQY8aSreemmMJhhx20xtpKlLrTzTXN9VMNzx/3uiFryg1vQvzJRtC5P6RlteUMnjJ3BYPMxUEdeAcz2/O3z1mIBtjbcvZdUKzQYMbMwl/Wn+7uI89N36THGq39SYjjqCSeWdP+VgJ8dPy5MfE4wB4qwkPBC1eljGWe0RtAy7Op9O+13PPeQ+ZhtbB+3IW7aWdmFUFGyOmtOYULzksqCdKjoW/sCBuFymbwH3LUkBQBDfNZHWEGUQCam4ZzYckvCHv0fBzPwkRCpknhSgRKtZuu/C8m3yxns2lhvFR8PFHi9uMoXQOndP4H6qrVHSftga3tRRDJUZryF/A9XrGo3I8VwumVOX9tIiQviuwUyMtaagRzmoHNfUU6T+7sjFjtb7Auw3s84gVnRsqGDYQ="
    # passphrase for packaging gpg secret key
    - secure: "pZmrxStWj0vXaG/YAyJORvxfaKQHvr+O+66yjFF52gQTVd2zNb83Mn4zDLNqMwU3nkXEKYuFbpXKbDSMX9zNbE7W/w1ARSa8MVXnMVM3jbj+OCaBu7fyVrA0tvT3EZkMh943paTRcSyPSzd61P3CNOkcY1RycDHBbJtNrzSdUbdAy6//TWgNxC66dxSeHASRJIIs49caxQssMMSGRgC5aGH4KLU5eSdP3wnWDEHr+aLqaI2DF2W3lNMI0WJwtGN6cLEYzAsA3BkoPoYRFDd4jjTpolVdrFBXRaT1EIg0FXjsvjyFrQfQLBIqvSx42H5w4rCIYoKYYgRgCKDATLK8XxPbFsgPKLVSHFD6t9ebuYacYxS20oMakkqj5e98qMIWe2vkm+V9YNeADIlhYT+NsF9Kug2B6pLK+U+Hhj6TldFpP18snPXttRKzsg9QrGbnBUVq2wv60U7/3pWs+T3tpr9bIFyaUYbRRAwl/hv2hVkFiSdsiLB6tJphbILB7EDKBCu1iK9PC9tlYoGrqptRxj6bmlawOvcnEKRtoPNJ9eyrvHPDd8FmmW6xWbq89zJ97Ztl7VR8CzNePqvG9vwdtJigXovuXfzu4CHX+jOt3jvllB6rMprsK5r++qBzh1SS24sYqo/APtUfoYdkleWhC+tSuhbucZb2yGUCMo/ZhDo="
  matrix:
    - TARGET_PLATFORM=debian/stretch
    - TARGET_PLATFORM=debian/jessie
    - TARGET_PLATFORM=debian/wheezy
    - TARGET_PLATFORM=ubuntu/xenial
    - TARGET_PLATFORM=ubuntu/trusty
before_install:
  - git clone -b v0.7.1 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - export PACKAGING_SECRET_KEY="$(openssl aes-256-cbc -K $encrypted_a39e3f1ee8ba_key -iv $encrypted_a39e3f1ee8ba_iv -in signing_key.asc.enc -d | base64)"
install: true
script: build_new_release
deploy:
  - provider: packagecloud
    username: "citusdata"
    repository: $PKG_REPOTYPE
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/releases"
    on:
      branch: "debian-cron"
      condition: -d "pkgs/releases"
  - provider: packagecloud
    username: "citusdata"
    repository: "$PKG_REPOTYPE-nightlies"
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/nightlies"
    on:
      branch: "debian-cron"
      condition: -d "pkgs/nightlies"
