sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  global:
    # GitHub ("Packaging") API token for citus-bot
    - secure: "zb6AHEUEvpCnWb4zRTsWTWVmMWNHkzz4c+UUgABaXYysJHCfBNiu5X4Da/jusCPY9GH4XFX8GPCiR69ZKw/LDnzHgXoH2pmda02CZM6SHjRGd0MrlBl0hF8YbHiBFi6/nH7kF0ODX+SepfJlFq8LQq6HVONz6QQl0FW0Rg1qnNaDMMi6L9NBBSDyuYCUdY05lgNeIyG8LyIErvlNA8U86VxOHp/KKbNaNx0Cs/tpDWNeW1v1rxa6EXtt8pxyc4u09V9csyFcglizkWEi98aqBTqyCa4hgIK3anog51vAg997cPOUu+ENUpwsio2JMorXalzNszBtpbO9u15+hLRHAoSL56hRdar3fTCuyyXpKapyNZ5Xxa8bYmgLDSJ2lS3zDl6fUfJWVqfzDWx1BuYVGjmJquYMVGKDiBu6iiOx7M/L8Kwof/ioe1LWro92a+S2KKgmXJfxNm4//F2EK+n++GNMZzOsfW+HSVhZ5sXt/tN9eOGmRQ4jWOZK7ycdpB+zMtxYDur/D46oLGAJhY88YqJaBbx0Jk0EMzSfM1eSoGcXEfLfwzGTm3MFnG/IJ3BPW1pkf5s2gMofUssGFitqnDZ7wlexrwA6qPMPIafW+yn5m4wwQwAxk20Y/kOREKHYDP6X6AbQNmfUk93/djYLjd/gGYLS3xvkNOLBWq2CCD8="
    # PGXN password for citusdata
    - secure: "tA0sEJpfzC6r4CcGegFyt0B16pGdhveVsZqyEBhF6niKojgw7b/sZC8SA0eQXAgYfSpQs3t+WCsitNW9Wgbot/xkZQltKFTY//YZRMvHNGQenmiOQ03KpCHaR9QqtS1ZziYNY1W4H+qVxTHKCHISTCEj/oq+U3w/rSMvxBz8yGtVedGtBvZP8JfC2AepAqJAwMPfR71bYbAXNIJqywR5Hmd0zB+nAKNaXUY7FkyyZm89zXrkjMY467RsNlf9V1BbwpNtyAHNIwES97qEqTiMMmutW62K54FjibH8GmktzcmN0FQnXPaZoPzMf95RcYTgc1FPbZqgZodWf73HezpkrBsNiZ6DzACER5meLVV39ehw92iOW7noMN7qTsmtM7q64ERSILPdcTrN/xR0oc9JmdCTdeo1san7p0StEz88G1S3oPVNIEgVz6wxpxySWMnGlvEAsHDtFDPC0A4RiNixPKZIJsvHQU4r54vieJHJpqGuWGyKJtNZ4yitW89a4GZCX3b4XKuUR2swscrIxuKKolABwcZgFanZXp16av3z2qmKdV/o8cNDL2+pdpkqGErjbWvPo+JMh3Ia87FeYvbVRj8WjBGs7NCsC4p9NtulnEKHoUrcjsD961r4Oo73ZB5oYKF+k1ZV86+Qw8Tgl3M+TxQN/tOscIQ6WPSKN3AOR80="
branches:
  only: ['pgxn-citus']
before_install:
  - git clone -b v0.7.13 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
install: true
script: release_pgxn
