sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  global:
    - PKG_REPOTYPE=enterprise
    # packagecloud API token for citus-bot
    - secure: "mW9G0JbHal27K0x+jledF3qQLwqtKy0cAc5oyEZ09faYorA9V1Hh7u4FDBNgjbuqDOWft1lIU24rSoOCq+F2mHRG+L5nYsBsHHLMDagshNBgVLYM6paRHa03yO6BIOJ7OPsUGpWSTqNG+imrAwFcqUTmTiwEr1A+dgHg4XUX2cJ/OYl7ZjWArZtD0jgjFuOVz9Hsi/EL3AP/xqKSRyARr3RWZqEsQCEVXSLTomosqMJzbVBpwwTdcFRcxX66T5p3soGZaP/zsE1g7VSTMvLv0qveF+ZSnX4eFIS0EJMs2eF2PvdBIqrwS3MYZNaVoWxJwWnO89SnPmzUBn9Jb35tNZ5fh7fQB4ZmT5wDsSTLDVwr2OOho95ByyFq+ZYRC8bkKkL8XYvF8b+pfkjFO05/hlCstK+Fr/JgUlAHlZLZZdVtkwygW9IuDq1nsuXl3F+6SgLRzxm0154epJtdy636a0ExOYvh6QVvVcvMaoHTxY+otCDRAkeopj1DPBKW3EsZHE3+3eZ0oB7NIbwHE3yYkSzXnJmhL+Iw0qleZ4qupAx9LVKFIMdon8pjQVk4rX5gHP9JOciR93mJQchA+Sht8MwWmC1Ayt/jkVmt43eSBjmExX9H4kJIbP9G6edCqaE1CJl1HK365/o2QJFcWXE7+GdEebkeyQqNCakqmqzvE+o="
    # GitHub ("Packaging") API token for Hanefi ( therefore not citus-bot )
    # The previous token was broken, I created a temporary and personal one to
    # release the 8.2.2 enterprise packages.
    - secure: "oq+iV5WMR5mc2ZgOnITmYAa7XOdfhtx5Efd2NTO9p+Y98luwrzU0MK+4QfkYnlEkBWhRGWKEn2qBR/CLrpfP0fqIi8UeJrP5zD7ORc7eoVH2zerkmaR6ilEwaEikVW+uqoEF739mXIVFtPhqr4rVL4b6U58u3iCAkoVAtHQTLuhTd5kuVayDxuk/2gdQLcbATtadnXK7HNTZXIjiXtsmeWsVvLgc12wwV2ItoCkXY4h+GmxfCKJLwkISsrRkpzYlnqHyonmm7maaQ+SF3ddiv0SJe5eFT6qDCExkO3KydUCOU8fLSnx/JvzOAQenVdFumaB8rT/0B5XTjrrm3vj+T6UvRRPgwjOLM6i/45Trm4WOvhPEl7MCMUShlufBTZz6n6aYjASjCQOpawILMVuXADeU03yEYSj2gpggbffZWqxT5wpY0MDr1cSSS+Td0l1n64OxQc5jBkwwX3PDVdlw/UM8kxPrjQ9iu+UQfrLHhA+5ROpMp5OgJo3S7TxGCpVPELKBn6M84WN06NnMPoUGftL2uDRVrTSjvErHRaLbhLeTeVLMqabBIZVzD/RHKx+zmENhy7dShNENIWhhCzz2KMY6pUf+Hgo2S0f1vl5tzEn1PH3j69JwcEgvKz+dnxviTaNpe0/x451xpMjJ7C8p7pGFs/LDr3A0Z3CbPGk96WA="
    # passphrase for packaging gpg secret key
    - secure: "pZmrxStWj0vXaG/YAyJORvxfaKQHvr+O+66yjFF52gQTVd2zNb83Mn4zDLNqMwU3nkXEKYuFbpXKbDSMX9zNbE7W/w1ARSa8MVXnMVM3jbj+OCaBu7fyVrA0tvT3EZkMh943paTRcSyPSzd61P3CNOkcY1RycDHBbJtNrzSdUbdAy6//TWgNxC66dxSeHASRJIIs49caxQssMMSGRgC5aGH4KLU5eSdP3wnWDEHr+aLqaI2DF2W3lNMI0WJwtGN6cLEYzAsA3BkoPoYRFDd4jjTpolVdrFBXRaT1EIg0FXjsvjyFrQfQLBIqvSx42H5w4rCIYoKYYgRgCKDATLK8XxPbFsgPKLVSHFD6t9ebuYacYxS20oMakkqj5e98qMIWe2vkm+V9YNeADIlhYT+NsF9Kug2B6pLK+U+Hhj6TldFpP18snPXttRKzsg9QrGbnBUVq2wv60U7/3pWs+T3tpr9bIFyaUYbRRAwl/hv2hVkFiSdsiLB6tJphbILB7EDKBCu1iK9PC9tlYoGrqptRxj6bmlawOvcnEKRtoPNJ9eyrvHPDd8FmmW6xWbq89zJ97Ztl7VR8CzNePqvG9vwdtJigXovuXfzu4CHX+jOt3jvllB6rMprsK5r++qBzh1SS24sYqo/APtUfoYdkleWhC+tSuhbucZb2yGUCMo/ZhDo="
  matrix:
    - TARGET_PLATFORM=el/7
    - TARGET_PLATFORM=el/6
    - TARGET_PLATFORM=ol/7
    - TARGET_PLATFORM=ol/6
before_install:
  - git clone -b v0.7.7 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - export PACKAGING_SECRET_KEY="$(openssl aes-256-cbc -K $encrypted_a39e3f1ee8ba_key -iv $encrypted_a39e3f1ee8ba_iv -in signing_key.asc.enc -d | base64)"
install: true
script: build_new_release && build_new_nightly
deploy:
  - provider: packagecloud
    username: "citusdata"
    repository: $PKG_REPOTYPE
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/releases"
    on:
      branch: "redhat-enterprise"
      condition: -d "pkgs/releases"
  - provider: packagecloud
    username: "citusdata"
    repository: "$PKG_REPOTYPE-nightlies"
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/nightlies"
    on:
      branch: "redhat-enterprise"
      condition: -d "pkgs/nightlies"
