sudo: required
services: [docker]
language: perl
perl: "5.18"
arch: amd64
os: linux
dist: focal
env:
  matrix:
    - TARGET_PLATFORM=centos,8
    - TARGET_PLATFORM=centos,7
    - TARGET_PLATFORM=debian,bullseye
    - TARGET_PLATFORM=debian,buster
    - TARGET_PLATFORM=debian,stretch
    - TARGET_PLATFORM=oraclelinux,8
    - TARGET_PLATFORM=oraclelinux,7
    - TARGET_PLATFORM=ubuntu,focal
    - TARGET_PLATFORM=ubuntu,bionic
    - TARGET_PLATFORM=pgxn
before_install:
  - echo $TARGET_PLATFORM > os-list.csv
install: true
script:
  - ./update_dockerfiles
  - git add --intent-to-add dockerfiles
  - git diff --exit-code dockerfiles
  - git checkout -- dockerfiles
  - ./update_images
  - ./ci/push_images
