name: Build Package

env:
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"
  PACKAGING_SECRET_KEY: "${{ secrets.PACKAGING_SECRET_KEY }}"
  PACKAGE_CLOUD_REPO_NAME: "sample"
  PACKAGE_ENCRYPTION_KEY: "${{ secrets.PACKAGE_ENCRYPTION_KEY }}"
  PACKAGING_PASSPHRASE: "${{ secrets.PACKAGING_PASSPHRASE }}"
  DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
  DOCKERHUB_USER_NAME: "${{ secrets.DOCKERHUB_USER_NAME }}"
on:
  push:
    branches: "**"

  workflow_dispatch:

jobs:
  build_package:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        TARGET_PLATFORM:
          - centos,8
          - centos,7
          - debian,bullseye
          - debian,buster
          - debian,stretch
          - oraclelinux,8
          - oraclelinux,7
          - ubuntu,focal
          - ubuntu,bionic
          - ubuntu,xenial
          - pgxn

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install wheel for el/8
        if: matrix.TARGET_PLATFORM  == 'centos,8'
        run: python -m pip install wheel

      - name: Update and check dockerfiles
        run: |
          ./update_dockerfiles
          git add --intent-to-add dockerfiles
          git diff --exit-code dockerfiles

      - name: Build images
        run: |
          git checkout -- dockerfiles
          ./update_images
        env:
          TARGET_PLATFORM: ${{ matrix.TARGET_PLATFORM }}
      - name: Push images
        run: ./ci/push_images
