name: Build and publish citus community nightly packages

env:
  MAIN_BRANCH: "all-citus"
  PACKAGE_CLOUD_REPO_NAME: "citusdata/community-nightlies"
  PACKAGE_CLOUD_API_TOKEN: ${{ secrets.PACKAGE_CLOUD_API_TOKEN }}
  PACKAGING_PASSPHRASE: ${{ secrets.PACKAGING_PASSPHRASE }}
  PACKAGING_SECRET_KEY: ${{ secrets.PACKAGING_SECRET_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  DOCKERHUB_USER_NAME: ${{ secrets.DOCKERHUB_USER_NAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build_package:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - el/7
          - el/8
          - debian/stretch
          - debian/buster
          - debian/bullseye
          - ubuntu/bionic
          - ubuntu/focal
          - ubuntu/jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # This step is to fetch the images unanonymously to have higher bandwidth
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Clone tools branch
        run: git clone -b v0.8.21 --depth=1  https://github.com/citusdata/tools.git tools

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install python requirements
        run: python -m pip install -r tools/packaging_automation/requirements.txt

      - name: Build packages
        run: |
          python -m  tools.packaging_automation.citus_package \
          --gh_token "${GH_TOKEN}" \
          --platform "${{ matrix.platform }}" \
          --build_type "nightly" \
          --secret_key "${PACKAGING_SECRET_KEY}" \
          --passphrase "${PACKAGING_PASSPHRASE}" \
          --output_dir "$(pwd)/packages/" \
          --input_files_dir "$(pwd)"
          
