name: Release
on:
  push:
    branches: "**"
jobs:
  release:
    name: Release on GitHub and PGXN
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Bundle the Release
        id: bundle
        run: pgxn-bundle
      - name: Release on PGXN
        env:
          #Will bechanged after testing this pipeline on the next release
          #          MAIN_BRANCH: "pgxn-citus"
          MAIN_BRANCH: issue_714
          PGXN_USERNAME: ${{ secrets.PGXN_USER_NAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: |
          CURRENT_BRANCH="${GITHUB_REF##*/}"
          if [[ "${CURRENT_BRANCH}" == "${MAIN_BRANCH}" ]]
          then
            pgxn-release
          else
            echo "Distro will not be released since current branch '${CURRENT_BRANCH}' is different from main branch '${MAIN_BRANCH}'"
          fi
