# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone Tools branch
        run: git clone --branch tools-transition https://github.com/citusdata/tools.git

      - name: install requirements
        run: python -m pip install -r tools/python/requirements.txt

      - name: Execute Package Properties Update
        run: |
              git config --global user.email "gindibay@microsoft.com"
              git config --global user.name "Gurkan Indibay"
              chmod +x ./tools/bash/update_package_properties.sh && ./tools/bash/update_package_properties.sh
