# This is a basic workflow to help you get started with Actions

name: CI

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PRJ_NAME: ${{ github.event.inputs.project_name }}
  TAG_NAME: ${{ github.event.inputs.project_name }}
  PRJ_VER: ${{ github.event.inputs.project_version }}
  FANCY: ${{ github.event.inputs.fancy }}
  FANCY_VERSION_NO: ${{ github.event.inputs.fancy_version_no }}
  MICROSOFT_EMAIL: ${{ github.event.inputs.microsoft_email }}
  NAME: ${{ github.event.inputs.name }}

# Controls when the action will run.
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      project_name:
        description: 'The github repository name'
      tag_name:
        description: 'The tag name on the project repo to be released'
      project_version:
        description: 'Version number to be released e.g 10.0.3'
      fancy:
        description: 'If fancy versioning is required set it "True"'
        default: 'False'
      fancy_version_no:
        description: 'If fancy versioning is True, then it should be set e.g 1'
        default: '1'
      microsoft_email:
        description: 'Email to be written on changelogs'
        default: 'gindibay@microsoft.com'
      name:
        description: 'Name to be written on changelogs'
        default: 'Gurkan Indibay'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone Tools branch
        run: git clone --branch tools-transition https://github.com/citusdata/tools.git

      - name: install requirements
        run: python -m pip install -r tools/python/requirements.txt

      - name: Execute Package Properties Update
        run: |
              git config --global user.email "gindibay@microsoft.com"
              git config --global user.name "Gurkan Indibay"
              chmod +x ./tools/bash/update_package_properties.sh && ./tools/bash/update_package_properties.sh
