name: Update Version on PGXN Config Files

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      project_version:
        description: "Version number to be released e.g 10.0.3"
        required: true

jobs:
  update_pgxn:
    name: Update pgxn configuration
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Clone Tools branch
        run: git clone --depth 1 --branch update_properties_fixes https://github.com/citusdata/tools.git

      - name: Install Python requirements
        run: python -m pip install -r tools/packaging_automation/requirements.txt

      - name: Set git name and email
        run: |
          git config --global user.email "${{ github.event.inputs.microsoft_email }}" && \
          git config --global user.name "${{ github.event.inputs.name }}"

      - name: Update pgxn files
        run: |
          python -m tools.packaging_automation.update_pgxn \
          --prj_ver ${{ github.event.inputs.project_version }} \
          --gh_token ${GH_TOKEN} \
          --pipeline \
          --exec_path "$(pwd)"
