name: Update Package Properties

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PRJ_NAME: ${{ github.event.inputs.project_name }}
  TAG_NAME: ${{ github.event.inputs.tag_name }}
  PRJ_VER: ${{ github.event.inputs.project_version }}
  FANCY: ${{ github.event.inputs.fancy }}
  FANCY_VERSION_NO: ${{ github.event.inputs.fancy_version_no }}
  MICROSOFT_EMAIL: ${{ github.event.inputs.microsoft_email }}
  NAME: ${{ github.event.inputs.name }}

on:

  workflow_dispatch:
    inputs:
      project_name:
        description: 'The github repository name'
      tag_name:
        description: 'The tag name on the project repo to be released'
      project_version:
        description: 'Version number to be released e.g 10.0.3'
      fancy:
        description: 'If fancy versioning is required set it "True"'
        default: 'False'
      fancy_version_no:
        description: 'If fancy versioning is True, then it should be set e.g 1'
        default: '1'
      microsoft_email:
        description: 'Email to be written on changelogs'
        default: 'gindibay@microsoft.com'
      name:
        description: 'Name to be written on changelogs'
        default: 'Gurkan Indibay'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone Tools branch
        run: git clone --branch tools-transition https://github.com/citusdata/tools.git

      - name: Install Python requirements
        run: python -m pip install -r tools/python/requirements.txt

      - name: Update Package Properties
        run: |
          git config --global user.email "${MICROSOFT_EMAIL}"
          git config --global user.name "${NAME}"
          chmod +x ./tools/bash/update_package_properties.sh && ./tools/bash/update_package_properties.sh
